### ISSUE TITLE
I can not compile aws-c-event-stream, how to solve the problem?

### ISSUE THREAD

**Issue by lml0001** [awslabs/aws-c-event-stream#34]
lumenle@lumenle-virtual-machine:~/lib/aws-c-event-stream/build$ cmake ..
CMake Error at /home/lumenle/lib/aws-c-common/cmake/aws-c-common-config.cmake:10 (include):
  include could not find load file:

    /home/lumenle/lib/aws-c-common/cmake/static/@PROJECT_NAME@-targets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:87 (find_package)

CMake Error at /home/lumenle/lib/aws-checksums/cmake/aws-checksums-config.cmake:4 (include):
  include could not find load file:

    /home/lumenle/lib/aws-checksums/cmake/static/@CMAKE_PROJECT_NAME@-targets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:88 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/lumenle/lib/aws-c-event-stream/build/CMakeFiles/CMakeOutput.log".
See also "/home/lumenle/lib/aws-c-event-stream/build/CMakeFiles/CMakeError.log".

**Comment by graebm** [comment]
aws-c-event-stream has 2 dependencies that need to be installed first. I've add build instructions to the README...
https://github.com/awslabs/aws-c-event-stream/pull/35/commits/e377d8b306f1112c0e4cacb9c3eb634868ce115e

```
git clone git@github.com:awslabs/aws-c-common.git
cmake -DCMAKE_PREFIX_PATH=<install-path> -DCMAKE_INSTALL_PREFIX=<install-path> -S aws-c-common -B aws-c-common/build
cmake --build aws-c-common/build --target install

git clone git@github.com:awslabs/aws-checksums.git
cmake -DCMAKE_PREFIX_PATH=<install-path> -DCMAKE_INSTALL_PREFIX=<install-path> -S aws-checksums -B aws-checksums/build
cmake --build aws-checksums/build --target install

git clone git@github.com:awslabs/aws-c-event-stream.git
cmake -DCMAKE_PREFIX_PATH=<install-path> -DCMAKE_INSTALL_PREFIX=<install-path> -S aws-c-event-stream -B aws-c-event-stream/build
cmake --build aws-c-event-stream/build --target install
```

**Comment by graebm** [comment]
instructions now available in readme: https://github.com/awslabs/aws-c-event-stream/#building

**Comment by h3rbg3** [comment]
I have the exact same issue.  These instructions work up until aws-c-event-stream.
From what I can see, aws-sdk-cpp has installed the shared libraries but in the case of aws-c-event-stream it is missing the static library cmake target.

```
-- Found AWS SDK for C++, Version: 1.7.347, Install Root:/usr/local, Platform Prefix:, Platform Dependent Libraries: pthread;crypto;ssl;z;curl
-- Components specified for AWSSDK: s3, application wll be depending on libs: aws-cpp-sdk-s3;aws-cpp-sdk-core
-- Try finding aws-cpp-sdk-core
CMake Error at /usr/local/lib/aws-c-event-stream/cmake/aws-c-event-stream-config.cmake:8 (include):
  include could not find load file:

    /usr/local/lib/aws-c-event-stream/cmake/static/aws-c-event-stream-targets.cmake
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CMakeFindDependencyMacro.cmake:48 (find_package)
  /usr/local/lib/cmake/aws-cpp-sdk-core/aws-cpp-sdk-core-config.cmake:2 (find_dependency)
  /usr/local/lib/cmake/AWSSDK/AWSSDKConfig.cmake:303 (find_package)
  CMakeLists.txt:10 (find_package)


-- Found aws-cpp-sdk-core
-- Try finding aws-cpp-sdk-s3
-- Found aws-cpp-sdk-s3
-- Configuring incomplete, errors occurred!

```

**Comment by h3rbg3** [comment]
I was able to overcome the issue by:

```
git clone git@github.com:awslabs/aws-c-event-stream.git
cd aws-c-event-stream
mkdir build && cd build
cmake -DCMAKE_PREFIX_PATH=/usr/local/ -DCMAKE_INSTALL_PREFIX=/usr/local/ ../
make
sudo make install

**Comment by rccarper** [comment]
Hello, it sounds like the issue you're running into is related to the C++ SDK.  If that's true, because this ticket is for building this library individually, would you be able to open a new issue on the C++ SDK repo?  Also, just to be sure, it sounds like the issue you're describing here is the same one that you encountered here: https://github.com/awslabs/aws-c-event-stream/issues/7.  Is that correct?

**Comment by h3rbg3** [comment]
It's not immediately clear from the docs what "install-dir" means generally
on ubuntu.  I now know that is /usr/local --

I've been able to correct this and build the stuff myself.  I will open a
ticket.  The issue is specifically the S3 component, which relies on these
dependencies introduced in 1.7.0

Herb Gilliland
Lead Software Developer
Bloomfield Robotics
herb@bloomfield.ai | bloomfield.ai

CONFIDENTIAL: This email, including attached files, may contain
confidential information and is intended only for the use of the individual
and/or entity to which it is addressed. If you are not the intended
recipient, disclosure, copying, use, or distribution of the information
included in this email is prohibited. Please delete this email immediately
and notify us by replying to this email.
