### ISSUE TITLE
aws-c-event-stream not found

### ISSUE THREAD

**Issue by stephanecharette** [awslabs/aws-c-event-stream#65]
I'm attempting to use dynamodb on a NVIDIA Jetson NX which runs the ARM version of Ubuntu 18.04.

I've built and installed the AWS SDK CPP v1.8.174.  But when I attempt to use `FIND_PACKAGE (AWSSDK COMPONENTS dynamodb REQUIRED)` in my CMakeLists.txt file, I've run into this error:

```
-- Found AWS SDK for C++, Version: 1.8.174, Install Root:/usr, Platform Prefix:, Platform Dependent Libraries: pthread;crypto;ssl;z;curl
-- Components specified for AWSSDK: dynamodb, application will be depending on libs: aws-cpp-sdk-dynamodb;aws-cpp-sdk-core
-- Try finding aws-cpp-sdk-core
CMake Error at /snap/cmake/847/share/cmake-3.20/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  Found package configuration file:

    /usr/lib/aws-c-event-stream/cmake/aws-c-event-stream-config.cmake

  but it set aws-c-event-stream_FOUND to FALSE so package
  "aws-c-event-stream" is considered to be NOT FOUND.  Reason given by
  package:

  The following imported targets are referenced, but are missing:
  AWS::aws-c-io

Call Stack (most recent call first):
  /usr/lib/cmake/aws-cpp-sdk-core/aws-cpp-sdk-core-config.cmake:2 (find_dependency)
  /usr/lib/cmake/AWSSDK/AWSSDKConfig.cmake:292 (find_package)
  CMakeLists.txt:48 (FIND_PACKAGE)
```

Being unfamiliar with the AWS SDK, I could use some assistance.  Is aws-c-event-stream supposed to be part of the AWS SDK?  Anyone know how to fix this problem?

**Comment by jmklix** [comment]
I see that you opened [this](https://github.com/aws/aws-sdk-cpp/issues/1609) issue as well on the aws-sdk-cpp repo. That is likely the correct place to fix this error as it's likely a problem with the cmake in that sdk. I noticed in that issue that you said you are no longer working on that project, but I wanted to ask if you or anyone else is still running into this error?

If anyone runs into this same error after this issue is closed please open a new issue on the aws-sdk-cpp repo
